set nocompatible
set incsearch
set nu

"set tw=80
"set textwidth=80
set ruler

set noerrorbells visualbell t_vb=
set tags=.ctags

set softtabstop=2
set shiftwidth=2
set expandtab
set tabstop=2

set autoindent
" this lets us use F10 to turn off autoindent on paste
set pastetoggle=<F10>

" removes trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e
